version: 1
accounts:
  - name: alice
    coins: ["20000token", "200000000stake"]
  - name: bob
    coins: ["10000token", "100000000stake"]
  - name: star
    coins: ["10000token", "100000000stake"]
validators:
  - name: alice
    bonded: "100000000stake"
genesis:
  chain_id: "fairyring"
  app_state:
    gov:
      voting_params:
        voting_period: "30s"
    pricefeed:
      params:
        source_channel: "channel-0"
      symbol_requests: [{"symbol": "ETH", "oracle_script_id": 396, "block_interval":  10, "price_step": 1}, {"symbol": "BTC", "oracle_script_id": 396, "block_interval":  10, "price_step": 1}]
client:
  openapi:
    path: "docs/static/openapi.yml"
  typescript:
    path: "ts-client"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5token", "100000stake"]
